# 'course title': [course_id, disabled]
_courses = {
'--- Informācijas un datu lietpratība ---': [0, True],
'Datu, informācijas un digitālā satura izvērtēšana': [72, False],
'Padziļināta informācijas pratība': [69, False],
'Informācijpratības pamati': [14, False],
# 'Datu pratības pamati': [58, False], pirmais jautājums A oteais jautājums arī A
'Datu analīze ar Excel': [48, False],
'Datu analīze lēmumu pieņemšanai': [50, False],
'Izklājlapu izmantošanas iespējas datu analīzei': [8, False],
'Ievads datu analītikā': [6, False],
'Datu pratība': [5, False],
# 'Total Data Quality Specialization': [71, False], nav pabeigts
'Datu ieguve un zināšanu atklāšana': [51, False],
'Matemātiskās metodes datu analīzē': [49, False],
'Datu analītika ar Python': [82, False],
'Informācijas tehnoloģijas pamatizglītībā': [79, False],
'--- Komunikācija un sadarbība ---': [0, True],
'Komunikācija 21.gadsimta darba vietā': [12, False],
'Google disks': [13, False],
'Tehnoloģijas labklājībai: IKT loma ilgtspējīgas attīstības mērķu sasniegšanā': [85, False],
'Tiešsaistes mācības un mācīšanās': [9, False],
'Digitālās identitātes pārvaldība': [19, False],
'--- Digitālā satura radīšana ---': [0, True],
'Stāstniecības lietpratība (The Craft of Storytelling)': [83, False],
'Tiešsaistes mācību pamati': [63, False],
'Grafiskie elementi dizainā: krāsu teorija un attēlu formāti': [60, False],
'Digitālais dizains': [37, False],
'Mācību dizains: digitālie mediji, jaunie rīki un tehnoloģijas': [36, False],
'Video, audio un infografiku veidošana tiešsaistes mācībām': [35, False],
'Lietotāju pieredzes psiholoģiskais pamats': [24, False],
'Sociālie mediji un digitālā mārketinga pamati': [39, False],
'Sadarbības pedagoģija mācību dizainam': [38, False],
'Tviters un Youtube mārketings': [40, False],
'Python pamati datu apstrādei': [47, False],
'Excel un VBA datu apstrādes automatizācijai': [44, False],
'Programmēšanas valodas C++ pamati': [43, False],
'Programmēšanas valodas Python pamati': [42, False],
'--- Drošība ---': [0, True],
'Datortīkla aizsardzības pamatprincipi': [61, False],
'Jūras kiberdrošība': [22, False],
# 'Digitālā kriminālistika': [57, False], nav pareizs formāts
'Privātums, datu aizsardzība un informācijas drošība': [23, False],
'Kiberdrošība un e-mācību vide': [20, False],
'Datu drošība informāciju tehnoloģijās': [46, False],
# 'Digitālie rīki un labklājība': [80, False], nav pareizs formāts
'Ilgtspējīga digitālā inovācija': [25, False],
'--- Problēmu risināšana ---': [0, True],
'Ievads lietotāju pieredzē': [55, False],
# 'Problēmu risināšanas metodes': [26, False], nav datu
'Lietotāju pieredzes dizains': [56, False],
'Kuģa radiolokācijas sistēmu izmantošana grafiskās informācijas manuālai apstrādei': [28, False],
'Tehnoloģijas un mākslīgā intelekta rīki elektroniskajā komercijā': [27, False],
'Radoša problēmu risināšana': [31, False],
'4EM modelēšana': [30, False],
'Digitālā transformācija un tehnoloģiskais forsaits': [70, False],
'Visaptverošā kvalitātes vadība': [66, False],
'Nākotnes darba dizains': [32, False],
}
